### ISSUE TITLE
With SAP JVM java memory assistant does not generate OOM on breach of threshold

### ISSUE THREAD

**Issue by unmarshall** [SAP/java-memory-assistant#11] opened 2019-11-06 04:24 UTC
We are currently using buildpack that is provided by SAP which internally uses SAP JVM. 
According to documentation at:
https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-java_memory_assistant.md, one can configure thresholds for heap-dump generation with something like:
`JBP_CONFIG_JAVA_MEMORY_ASSISTANT: '{enabled : true, agent : { thresholds : { old_gen : +20%/2m } } }'`
Unfortunately, this does not appear to be working.

We get an error like the below:
`java.lang.IllegalArgumentException: The value '85%/1m' is invalid for the 'jma.thresholds.heap' property: cannot parse the value '85%/1m' as percentage threshold: it must follow the Java pattern '(\d*\.?\d*\d)%'

2019-10-23T18:51:56.18+0530 [APP/PROC/WEB/0] ERR com.sap.jma.Agent#ERROR: JavaMemoryAssistant cannot start
   2019-10-23T18:51:56.18+0530 [APP/PROC/WEB/0] ERR java.util.NoSuchElementException: The memory pool 'CodeHeap 'non-nmethods'' is not known for the 'SAP_8_X' JVM`

**Comment by TimGerlach** [comment] 2019-11-06 07:28
Hi @unmarshall, can you please provide the exact `JBP_CONFIG_JAVA_MEMORY_ASSISTANT` configuration used to deploy your application?

**Comment by unmarshall** [comment] 2019-11-06 07:37
Hi @TimGerlach 

I have already provided the exact configuration in the original description of this issue. Are you looking for anything specific?

Best Regards,
Madhav

**Comment by mmanciop** [comment] 2020-02-26 12:58
@unmarshall the issue is that, instead of `m`, you should use `MB` to denote megabytes. The readme is unfortunately incorrect there :-)

**Comment by mmanciop** [comment] 2020-03-16 20:21
Actually, I was wrong in my previous message. I just tried that very same configuration and it works for me. I am closing the issue as I cannot reproduce. @unmarshall, if you can reproduce, please reopen!

**Closed by mmanciop** 2020-03-16 20:21 UTC
